### ISSUE TITLE
Rename 'selected' instances?

### ISSUE THREAD

**Issue by ryanbelisle** [exevil/sketch-rename-instances#2]
First off, thanks for creating this plugin!

**I have an idea if you are open to it?**
"Rename Selected Instances"

I'd love to be able to just choose certain symbols and rename vs my entire Sketch file. Sometimes I  purposely rename the instances so the symbol names make sense in context of how it's being used. Also, when importing into Flinto, Principle, etc, it helps to have unique names for the symbols. 

Being able to select just the symbols you want to rename would be really beneficial.

Thanks,
Ryan

**Comment by exevil** [comment]
Hey @ryanbelisle!

Thanks a lot for these kind words. You can now download [the latest release](https://github.com/exevil/sketch-rename-instances/archive/v.1.0.zip) with requested functionality and some improvements.

Best,
VD
