### ISSUE TITLE
Rename instances of selected symbol / Rename all instances in current page only

### ISSUE THREAD

**Issue by richardbruskowski** [exevil/sketch-rename-instances#3]
I love this plugin, it is such a time saver. But since nested symbols are a thing, I often need to rename nested symbol instances so the name is short enough to be readable in the "Overrides" panel. (My typical symbol names are way too long, as they are put in order with with a certain naming convention ("kit/category/component-name/includes/item")). The following features could be really useful to help designers keep their design system kits tidy and neat:

- Additionally to the already implemented feature "Rename Selected Instances", I think the option to rename all instances of selected symbols only would be really useful. As the symbols which are meant to be nested ("includes" or "atoms") are often different from the ones which are meant to be placed in the layout directly ("components").
- Another additional option might be, to rename all instances of all symbols in the currently selected page only. Might be even more useful, as the designer could use the function on his layout pages, while excluding the Symbol page, thus keeping the "Overrides" panel labels intact.

 The user would then have these four choices:
- Rename all instances 
- Rename all instances in current page
- Rename selected instances
- Rename all instances of selected symbols

**Comment by exevil** [comment]
Hey @richardbruskowski!

Thanks for complex feedback, I really appreciate it. I've added commands that you asked so please enjoy the new functionality.

Cheers,
VD
