### ISSUE TITLE
Renaming also affects nested symbols

### ISSUE THREAD

**Issue by cmyk** [exevil/sketch-rename-instances#4]
If you rename symbols that have nested symbols, all symbols get renamed, also the ones inside the symbol you intend to rename. This should not be the default behavious imho.

**Comment by exevil** [comment]
@cmyk: Hey Philipp! Thanks for the feedback, totally agreed. It's fixed now, enjoy!

**Comment by cmyk** [comment]
@exevil you are ©awesome! :)
