### ISSUE TITLE
Does not work on artboards converted to symbols

### ISSUE THREAD

**Issue by leannegunn** [exevil/sketch-rename-instances#5]
I use a lot of artboards converted to symbols which aren't on my Symbols page, where I would still like instances to be renamed. This plugin stopped working when the #4 Renaming also affects nested symbols fix was applied.  Is there a way to exclude symbols NOT on the symbols page?

**Comment by exevil** [comment]
Hey Leanne!

Hopefully someday I can get some time to make a small preferences window and let user to configure settings like this or like asked in #4. But for now I updated the plugin to rename all instances that placed outside of the Symbols page.

Enjoy!
