### ISSUE TITLE
Minor issue with result message text

### ISSUE THREAD

**Issue by someToast** [exevil/sketch-rename-instances#8]
displayResultMessage() checks for the renamed count to correctly set “instance” vs. “instances” in the message string, but has/have should be rolled in there too to avoid “1 instance have been renamed”

`var instancesTitle = renamedCount == 1 ? " instance has" : " instances have"
context.document.showMessage(renamedCount + instancesTitle + " been renamed")
`

**Comment by exevil** [comment]
Hey! Thanks for the feedback. Fixed!
