### ISSUE TITLE
No Instances found

### ISSUE THREAD

**Issue by pixtur** [exevil/sketch-rename-instances#9]
This plugin is precisely what I needed. Does it work with nested Symbols, eg. Symbold embedded in other symbols? It doesn't work for me: "No Instances to rename". 

I'm using Sketch 48.2

**Comment by Ashugeo** [comment]
Yep, that would be great 🙂

**Comment by exevil** [comment]
Hey guys!

Thanks for the feedback, but regarding the closed #4 it's an expected behavior. Many people are manually naming their nested symbols to put in order overrides inspector. That's why the plugin is skipping it, sorry.

Cheers.

**Comment by Ashugeo** [comment]
You're right! I actually came to the same conclusion minutes after posting my comment… I agree, it's more useful that way 🙂
